#
# Hacky make file to assist building thesis project
#
###################################################################################

all:
	pdflatex CaliSet\:\ The\ Calligraphy\ Dataset.tex
	pdflatex CaliSet\:\ The\ Calligraphy\ Dataset.tex
