#
# Hacky make file to assist building thesis project
#
###################################################################################

all:
	pdflatex CaliSet\:\ The\ Calligraphy\ Dataset.tex
	bibtex CaliSet\:\ The\ Calligraphy\ Dataset.aux 
	pdflatex CaliSet\:\ The\ Calligraphy\ Dataset.tex
